// <auto-generated />
using System;
using Fastfood.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fastfood.Migrations
{
    [DbContext(typeof(FastfoodContext))]
    [Migration("20191205025523_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fastfood.Models.Chitiethoadon", b =>
                {
                    b.Property<int>("ChitiethoadonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HoadonId")
                        .HasColumnType("int");

                    b.Property<int?>("MonanId")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("ChitiethoadonId");

                    b.HasIndex("HoadonId");

                    b.HasIndex("MonanId");

                    b.ToTable("Chitiethoadon");
                });

            modelBuilder.Entity("Fastfood.Models.Chitietphieunhap", b =>
                {
                    b.Property<int>("ChitietphieunhapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MonanId")
                        .HasColumnType("int");

                    b.Property<int?>("PhieunhapId")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("ChitietphieunhapId");

                    b.HasIndex("MonanId");

                    b.HasIndex("PhieunhapId");

                    b.ToTable("Chitietphieunhap");
                });

            modelBuilder.Entity("Fastfood.Models.Hoadon", b =>
                {
                    b.Property<int>("HoadonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanvienId")
                        .HasColumnType("int");

                    b.HasKey("HoadonId");

                    b.HasIndex("NhanvienId");

                    b.ToTable("Hoadon");
                });

            modelBuilder.Entity("Fastfood.Models.Monan", b =>
                {
                    b.Property<int>("MonanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("GiaMua")
                        .HasColumnType("int");

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nhacc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonanId");

                    b.ToTable("Monan");
                });

            modelBuilder.Entity("Fastfood.Models.Nhanvien", b =>
                {
                    b.Property<int>("NhanvienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanvienId");

                    b.ToTable("Nhanvien");
                });

            modelBuilder.Entity("Fastfood.Models.Phieunhap", b =>
                {
                    b.Property<int>("PhieunhapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanvienId")
                        .HasColumnType("int");

                    b.Property<int>("Tongtien")
                        .HasColumnType("int");

                    b.HasKey("PhieunhapId");

                    b.HasIndex("NhanvienId");

                    b.ToTable("Phieunhap");
                });

            modelBuilder.Entity("Fastfood.Models.Chitiethoadon", b =>
                {
                    b.HasOne("Fastfood.Models.Hoadon", "Hoadon")
                        .WithMany()
                        .HasForeignKey("HoadonId");

                    b.HasOne("Fastfood.Models.Monan", "Monan")
                        .WithMany()
                        .HasForeignKey("MonanId");
                });

            modelBuilder.Entity("Fastfood.Models.Chitietphieunhap", b =>
                {
                    b.HasOne("Fastfood.Models.Monan", "Monan")
                        .WithMany()
                        .HasForeignKey("MonanId");

                    b.HasOne("Fastfood.Models.Phieunhap", "Phieunhap")
                        .WithMany()
                        .HasForeignKey("PhieunhapId");
                });

            modelBuilder.Entity("Fastfood.Models.Hoadon", b =>
                {
                    b.HasOne("Fastfood.Models.Nhanvien", "Nhanvien")
                        .WithMany()
                        .HasForeignKey("NhanvienId");
                });

            modelBuilder.Entity("Fastfood.Models.Phieunhap", b =>
                {
                    b.HasOne("Fastfood.Models.Nhanvien", "Nhanvien")
                        .WithMany()
                        .HasForeignKey("NhanvienId");
                });
#pragma warning restore 612, 618
        }
    }
}
